language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
- 8
- node
env:
  - NODE_ENV=production
  - NPM_TAG=latest
before_install:
  - google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 &
install:
- npm --production=false install
- npm --production=false update
sudo: false
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script:
      - npm run lint
      - npm run docs
      - npm run tap
    - stage: deploy
      node_js: 8
      script: npm run build
      before_deploy:
      - VPKG=$($(npm bin)/json -f package.json version)
      - export VERSION=${VPKG}-prerelease.$(date +%Y%m%d%H%M%S)
      - npm --no-git-tag-version version $VERSION
      - if [[ "$TRAVIS_BRANCH" == hotfix/* ]]; then export NPM_TAG=hotfix; fi # double brackets are important for matching the wildcard
      - git config --global user.email "$(git log --pretty=format:'%ae' -n1)"
      - git config --global user.name "$(git log --pretty=format:'%an' -n1)"
      deploy:
        provider: npm
        skip_cleanup: true
        on:
          branch:
          - master
          - develop
          - hotfix/*
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: $NPM_TAG
